version: '3.8'

services:
  node-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"  # gRPC server
    networks:
      - grpc-net

  envoy:
    image: envoyproxy/envoy:v1.27-latest
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"  # frontend connects to this
    depends_on:
      - node-server
    networks:
      - grpc-net

networks:
  grpc-net:
    driver: bridge
