// source: issueReport.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require("google-protobuf");
var goog = jspb;
var global =
  (typeof globalThis !== "undefined" && globalThis) ||
  (typeof window !== "undefined" && window) ||
  (typeof global !== "undefined" && global) ||
  (typeof self !== "undefined" && self) ||
  function () {
    return this;
  }.call(null) ||
  Function("return this")();

goog.exportSymbol("proto.issue.issueRequest", null, global);
goog.exportSymbol("proto.issue.issueResponse", null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.issue.issueRequest = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.issue.issueRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.issue.issueRequest.displayName = "proto.issue.issueRequest";
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.issue.issueResponse = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.issue.issueResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.issue.issueResponse.displayName = "proto.issue.issueResponse";
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.issue.issueRequest.prototype.toObject = function (opt_includeInstance) {
    return proto.issue.issueRequest.toObject(opt_includeInstance, this);
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.issue.issueRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.issue.issueRequest.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        useremail: jspb.Message.getFieldWithDefault(msg, 1, ""),
        userdescription: jspb.Message.getFieldWithDefault(msg, 2, ""),
        category: jspb.Message.getFieldWithDefault(msg, 3, ""),
        subcategory: jspb.Message.getFieldWithDefault(msg, 4, ""),
        urgent: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
        timestamp: jspb.Message.getFieldWithDefault(msg, 6, ""),
        location: jspb.Message.getFieldWithDefault(msg, 7, ""),
        motordata: jspb.Message.getFieldWithDefault(msg, 8, ""),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.issue.issueRequest}
 */
proto.issue.issueRequest.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.issue.issueRequest();
  return proto.issue.issueRequest.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.issue.issueRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.issue.issueRequest}
 */
proto.issue.issueRequest.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setUseremail(value);
        break;
      case 2:
        var value = /** @type {string} */ (reader.readString());
        msg.setUserdescription(value);
        break;
      case 3:
        var value = /** @type {string} */ (reader.readString());
        msg.setCategory(value);
        break;
      case 4:
        var value = /** @type {string} */ (reader.readString());
        msg.setSubcategory(value);
        break;
      case 5:
        var value = /** @type {boolean} */ (reader.readBool());
        msg.setUrgent(value);
        break;
      case 6:
        var value = /** @type {string} */ (reader.readString());
        msg.setTimestamp(value);
        break;
      case 7:
        var value = /** @type {string} */ (reader.readString());
        msg.setLocation(value);
        break;
      case 8:
        var value = /** @type {string} */ (reader.readString());
        msg.setMotordata(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.issue.issueRequest.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.issue.issueRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.issue.issueRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.issue.issueRequest.serializeBinaryToWriter = function (message, writer) {
  var f = undefined;
  f = message.getUseremail();
  if (f.length > 0) {
    writer.writeString(1, f);
  }
  f = message.getUserdescription();
  if (f.length > 0) {
    writer.writeString(2, f);
  }
  f = message.getCategory();
  if (f.length > 0) {
    writer.writeString(3, f);
  }
  f = message.getSubcategory();
  if (f.length > 0) {
    writer.writeString(4, f);
  }
  f = message.getUrgent();
  if (f) {
    writer.writeBool(5, f);
  }
  f = message.getTimestamp();
  if (f.length > 0) {
    writer.writeString(6, f);
  }
  f = message.getLocation();
  if (f.length > 0) {
    writer.writeString(7, f);
  }
  f = message.getMotordata();
  if (f.length > 0) {
    writer.writeString(8, f);
  }
};

/**
 * optional string userEmail = 1;
 * @return {string}
 */
proto.issue.issueRequest.prototype.getUseremail = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};

/**
 * @param {string} value
 * @return {!proto.issue.issueRequest} returns this
 */
proto.issue.issueRequest.prototype.setUseremail = function (value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * optional string userDescription = 2;
 * @return {string}
 */
proto.issue.issueRequest.prototype.getUserdescription = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};

/**
 * @param {string} value
 * @return {!proto.issue.issueRequest} returns this
 */
proto.issue.issueRequest.prototype.setUserdescription = function (value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};

/**
 * optional string category = 3;
 * @return {string}
 */
proto.issue.issueRequest.prototype.getCategory = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};

/**
 * @param {string} value
 * @return {!proto.issue.issueRequest} returns this
 */
proto.issue.issueRequest.prototype.setCategory = function (value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};

/**
 * optional string subCategory = 4;
 * @return {string}
 */
proto.issue.issueRequest.prototype.getSubcategory = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};

/**
 * @param {string} value
 * @return {!proto.issue.issueRequest} returns this
 */
proto.issue.issueRequest.prototype.setSubcategory = function (value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};

/**
 * optional bool urgent = 5;
 * @return {boolean}
 */
proto.issue.issueRequest.prototype.getUrgent = function () {
  return /** @type {boolean} */ (
    jspb.Message.getBooleanFieldWithDefault(this, 5, false)
  );
};

/**
 * @param {boolean} value
 * @return {!proto.issue.issueRequest} returns this
 */
proto.issue.issueRequest.prototype.setUrgent = function (value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};

/**
 * optional string timestamp = 6;
 * @return {string}
 */
proto.issue.issueRequest.prototype.getTimestamp = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};

/**
 * @param {string} value
 * @return {!proto.issue.issueRequest} returns this
 */
proto.issue.issueRequest.prototype.setTimestamp = function (value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};

/**
 * optional string location = 7;
 * @return {string}
 */
proto.issue.issueRequest.prototype.getLocation = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};

/**
 * @param {string} value
 * @return {!proto.issue.issueRequest} returns this
 */
proto.issue.issueRequest.prototype.setLocation = function (value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};

/**
 * optional string motorData = 8;
 * @return {string}
 */
proto.issue.issueRequest.prototype.getMotordata = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};

/**
 * @param {string} value
 * @return {!proto.issue.issueRequest} returns this
 */
proto.issue.issueRequest.prototype.setMotordata = function (value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.issue.issueResponse.prototype.toObject = function (
    opt_includeInstance,
  ) {
    return proto.issue.issueResponse.toObject(opt_includeInstance, this);
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.issue.issueResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.issue.issueResponse.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        success: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
        message: jspb.Message.getFieldWithDefault(msg, 2, ""),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.issue.issueResponse}
 */
proto.issue.issueResponse.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.issue.issueResponse();
  return proto.issue.issueResponse.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.issue.issueResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.issue.issueResponse}
 */
proto.issue.issueResponse.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {boolean} */ (reader.readBool());
        msg.setSuccess(value);
        break;
      case 2:
        var value = /** @type {string} */ (reader.readString());
        msg.setMessage(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.issue.issueResponse.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.issue.issueResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.issue.issueResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.issue.issueResponse.serializeBinaryToWriter = function (message, writer) {
  var f = undefined;
  f = message.getSuccess();
  if (f) {
    writer.writeBool(1, f);
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(2, f);
  }
};

/**
 * optional bool success = 1;
 * @return {boolean}
 */
proto.issue.issueResponse.prototype.getSuccess = function () {
  return /** @type {boolean} */ (
    jspb.Message.getBooleanFieldWithDefault(this, 1, false)
  );
};

/**
 * @param {boolean} value
 * @return {!proto.issue.issueResponse} returns this
 */
proto.issue.issueResponse.prototype.setSuccess = function (value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};

/**
 * optional string message = 2;
 * @return {string}
 */
proto.issue.issueResponse.prototype.getMessage = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};

/**
 * @param {string} value
 * @return {!proto.issue.issueResponse} returns this
 */
proto.issue.issueResponse.prototype.setMessage = function (value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};

goog.object.extend(exports, proto.issue);
