/**
 * @fileoverview gRPC-Web generated client stub for issue
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: issueReport.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as issueReport_pb from './issueReport_pb'; // proto import: "issueReport.proto"


export class issueReporterClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorReportIssue = new grpcWeb.MethodDescriptor(
    '/issue.issueReporter/ReportIssue',
    grpcWeb.MethodType.UNARY,
    issueReport_pb.issueRequest,
    issueReport_pb.issueResponse,
    (request: issueReport_pb.issueRequest) => {
      return request.serializeBinary();
    },
    issueReport_pb.issueResponse.deserializeBinary
  );

  reportIssue(
    request: issueReport_pb.issueRequest,
    metadata?: grpcWeb.Metadata | null): Promise<issueReport_pb.issueResponse>;

  reportIssue(
    request: issueReport_pb.issueRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: issueReport_pb.issueResponse) => void): grpcWeb.ClientReadableStream<issueReport_pb.issueResponse>;

  reportIssue(
    request: issueReport_pb.issueRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: issueReport_pb.issueResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/issue.issueReporter/ReportIssue',
        request,
        metadata || {},
        this.methodDescriptorReportIssue,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/issue.issueReporter/ReportIssue',
    request,
    metadata || {},
    this.methodDescriptorReportIssue);
  }

}

